### PR TITLE
Save bugs fix

### LINKED ISSUE #469: You always save on shutdown

### LINKED ISSUE #470: Scene not saved on play

### PR DESCRIPTION
**Pull request by Sajdkick**
You now correctly save the scene on play, and don't always save after shuting down.

fixes #469 
fixes #470

### CODE REVIEW

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/Editor/Editor.cpp [hunk 1]
```diff
@@ -533,22 +533,19 @@ Entity* Editor::GetCamera() const {
 
 void Editor::Play() {
     Resources().Save();
-    editorState = Hymn().ToJson();
+    sceneState = Hymn().world.GetSaveJson();
```
Comment (Chainsawkitten) [inline src/Editor/Editor.cpp]: Now the scene is saved but the Hymn isn't (Hymn includes eg. a list of all scripts). Ideally both would be saved rather than just one.

Comment (Sajdkick) [reply src/Editor/Editor.cpp]: Can the hymn be altered when you play?

Comment (Chainsawkitten) [reply src/Editor/Editor.cpp]: No.

File: src/Engine/Entity/World.hpp [hunk 2]
```diff
@@ -99,7 +99,13 @@ class World {
          * @param filename The name of the file.
          */
         void Load(const std::string& filename);
-        
+
+        /// Load the world from a json.
+        /**
+         * @param node The json containing a scene to load.
+         */
+        void Load(Json::Value node);
```
Comment (Chainsawkitten) [inline src/Engine/Entity/World.hpp]: Could be passed as const-reference.

File: src/Editor/Editor.cpp (hunk 1 above)
Comment (Sajdkick) [reply src/Editor/Editor.cpp]: So why should we save it aswell?

File: src/Editor/Editor.cpp [hunk 3]
```diff
@@ -533,22 +533,19 @@ Entity* Editor::GetCamera() const {
...
     SetVisible(false);
     resourceView.HideEditors();
     resourceView.ResetScene();
     Managers().scriptManager->RegisterInput();
     Managers().scriptManager->BuildAllScripts();
 }
 
-void Editor::LoadEditorState() {
-    std::string path = Hymn().GetPath();
-    Hymn().Clear();
```
[the remark this answers is not in the document]
Comment (Chainsawkitten) [reply src/Editor/Editor.cpp]: No, since the hymn is never altered during play. We can keep the old one when returning to the editor.

**Comment by Chainsawkitten** [comment]
Now resources are instead dimissed and work is lost when playing since they're reloaded from disk when returning to the editor (but never saved). Either don't load from disk when returning (if they're never altered during gameplay (I don't think they should be?)) or store to memory during play.

**Comment by NinjaDanz3r** [comment]
iamheman
