### PR TITLE
Editor crash when mousepicking on empty mesh. #343

### LINKED ISSUE #343: Editor crash when mousepicking on empty mesh.
Editor crash when you select (with mousepicking) an entity with mesh component that has no model added.

How to reproduce:
Create and edit entity.
Add a mesh component without adding a model to the component.
Select the entity with mousepick in the editor screen.

### PR DESCRIPTION
**Pull request by LarsIngo**
Fixes #343

### CODE REVIEW

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/Editor/Editor.cpp [hunk 1]
```diff
@@ -543,25 +543,28 @@ void Editor::Picking() {
...
+                            entityIndex = i;
+                            if (entityAmount - i == 1) {
+                                resourceView.GetScene().entityEditor.SetEntity(Hymn().world.GetEntities().at(entityIndex));
+                                resourceView.GetScene().entityEditor.SetVisible(true);
+                                selectedEntity->GetComponent<Component::Mesh>()->SetSelected(true);
+                                break;
+                            }
+
+                        }
+                        else if (intersectDistance > 0.0f) {
```
Comment (andens) [inline src/Editor/Editor.cpp]: Should be placed on the previous line.

Comment (LarsIngo) [reply src/Editor/Editor.cpp]: Fixed, changed the code
