### PR TITLE
Blit depth buffer

### LINKED ISSUE #502: Debug drawing not working
All debug drawing has lots of artifacts and is only really drawn when moving. Probably due to some buffer not being cleared properly.

### PR DESCRIPTION
**Pull request by Chainsawkitten**
Blit depth buffer as well as the color buffer. This fixes debug drawing since it's reliant on the depth buffer and occurs on the backbuffer.

Fixes #502

### CODE REVIEW

File: src/Video/Renderer.cpp [hunk 1]
```diff
@@ -118,12 +118,22 @@ void Renderer::AntiAlias(RenderSurface* renderSurface) {
 }
 
 void Renderer::Present(RenderSurface* renderSurface) {
+    const glm::vec2 size = renderSurface->GetSize();
+    
+    /// @todo See if doing this with a fullscreen quad would be faster.
```
Comment (SwedishSock) [inline src/Video/Renderer.cpp]: Remember to make an issue about this.

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
