### PR TITLE
Fix texture overwrite

### LINKED ISSUE #443: Texture overwrite
When loading multiple textures they sometime get overwritten by the previous texture file. For example, after loading albedo, normal, metallic and roughness all textures might have become the albedo texture.

### PR DESCRIPTION
**Pull request by NinjaDanz3r**
Note: The fix introduces a non-intuitive behaviour where an assigned texture will be used in during a test run of a hymn but immediately revert back to its previous texture unless saved.
fixes #443

### CODE REVIEW

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [ResourceManager.hpp#L28](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/8d50a0e5e2eb44c1863586c1cb41272cc3600c42/src/Engine/Manager/ResourceManager.hpp#L28): Member variable 'ResourceManager::rectangle' is not initialized in the constructor. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AuninitMemberVar)
1. ![MINOR][MINOR] [ResourceManager.hpp#L28](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/8d50a0e5e2eb44c1863586c1cb41272cc3600c42/src/Engine/Manager/ResourceManager.hpp#L28): Member variable 'ResourceManager::cube' is not initialized in the constructor. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AuninitMemberVar)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/Engine/Texture/TextureAsset.cpp [hunk 1]
```diff
@@ -34,6 +35,9 @@ void TextureAsset::Load(const std::string& name) {
     
     // Get properties from meta file.
     Json::Value root;
+    if(!FileSystem::FileExists(std::string(filename + ".json").c_str())) {
```
Comment (NinjaDanz3r) [inline src/Engine/Texture/TextureAsset.cpp]: INFO keyword 'if' not followed by a single space [rule](http://localhost:9000/coding_rules#rule_key=vera%2B%2B%3AT008)

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 4 issues
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [ResourceManager.hpp#L28](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/7fadf0cb87c946439a488986f9745e5ab356ec17/src/Engine/Manager/ResourceManager.hpp#L28): Member variable 'ResourceManager::rectangle' is not initialized in the constructor. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AuninitMemberVar)
1. ![MINOR][MINOR] [ResourceManager.hpp#L28](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/7fadf0cb87c946439a488986f9745e5ab356ec17/src/Engine/Manager/ResourceManager.hpp#L28): Member variable 'ResourceManager::cube' is not initialized in the constructor. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AuninitMemberVar)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 4 issues
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 1 info

Watch the comments in this conversation to review them.

#### 3 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [ResourceManager.hpp#L28](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/00db860c684a96421a0a29af0fbfa907042ede64/src/Engine/Manager/ResourceManager.hpp#L28): Member variable 'ResourceManager::rectangle' is not initialized in the constructor. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AuninitMemberVar)
1. ![MINOR][MINOR] [ResourceManager.hpp#L28](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/00db860c684a96421a0a29af0fbfa907042ede64/src/Engine/Manager/ResourceManager.hpp#L28): Member variable 'ResourceManager::cube' is not initialized in the constructor. [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AuninitMemberVar)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
