### PR TITLE
Check if hymn exists before opening

### LINKED ISSUE #253: Crash when attempting to load hymn that does not exist
Steps to reproduce:
Open editor.
Click open hymn.
In the textbox for filename, enter the name of a hymn that doesn't exist
Crash.

### PR DESCRIPTION
**Pull request by Chainsawkitten**
Fixes #253

### CODE REVIEW

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/Editor/Editor.cpp [hunk 1]
```diff
@@ -652,12 +653,17 @@ void Editor::OpenHymn() {
...
     // Open hymn.
     if (!hymn.empty()) {
-        resourceView.ResetScene();
-        Hymn().Load(FileSystem::DataPath("Hymn to Beauty") + FileSystem::DELIMITER + "Hymns" + FileSystem::DELIMITER + hymn);
-        Resources().Clear();
-        Resources().Load();
-        LoadActiveScene();
-        resourceView.SetVisible(true);
+        std::string path = FileSystem::DataPath("Hymn to Beauty") + "/Hymns/" + hymn;
+        if (!FileSystem::FileExists((path + "/Hymn.json").c_str())) {
```
Comment (andens) [inline src/Editor/Editor.cpp]: Braces around single-statement body.
