### PR TITLE
Converted scene name in resources from string to string pointer.

### LINKED ISSUE #484: Crash when dereferencing invalid string
Reproduce:
- Open the game project
- Open resources
- Add a scene by right-clicking resources
- Select the added scene
- Add a model by right-clicking resources
- Crash in `SceneEditor::Show`, it seems that `scene` is a dangling pointer.

### PR DESCRIPTION
**Pull request by NinjaDanz3r**
This resolves #484

### CODE REVIEW

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [Resources.hpp#L112](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/3b19dc8e0d47cdf4c1f7875615c5a55a2bc33cec/src/Editor/Resources.hpp#L112): Unused private function: 'ResourceList::GetInstance' [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedPrivateFunction)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

File: src/Editor/GUI/Editors/ModelEditor.cpp [hunk 1]
```diff
@@ -106,7 +106,7 @@ void ModelEditor::Show() {
                     // Create resource.
                     ResourceList::Resource resource;
                     resource.type = ResourceList::Resource::SCENE;
-                    resource.scene = model->name + "Scene";
+                    resource.scene = new std::string(model->name + "Scene");
```
Comment (Chainsawkitten) [inline src/Editor/GUI/Editors/ModelEditor.cpp]: Memory leak since old scene string isn't deleted.
Instead just set the value.
*resource.scene = model->name + "Scene";

File: src/Editor/GUI/ResourceView.cpp [hunk 2]
```diff
@@ -206,7 +206,7 @@ void ResourceView::ShowResourceFolder(ResourceList::ResourceFolder& folder, cons
         if (ImGui::Selectable("Add scene")) {
             ResourceList::Resource resource;
             resource.type = ResourceList::Resource::SCENE;
-            resource.scene = "Scene #" + std::to_string(Resources().sceneNumber++);
+            resource.scene = new string("Scene #" + std::to_string(Resources().sceneNumber++));
```
Comment (Chainsawkitten) [inline src/Editor/GUI/ResourceView.cpp]: Memory leak. Just set the value.

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [Resources.hpp#L112](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/0256257ea6e5a1f38c978a37af65dd2f63fbafde/src/Editor/Resources.hpp#L112): Unused private function: 'ResourceList::GetInstance' [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedPrivateFunction)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [Resources.hpp#L112](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/3ab067123228b50847f9c6755dda34fd3115a006/src/Editor/Resources.hpp#L112): Unused private function: 'ResourceList::GetInstance' [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedPrivateFunction)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [Resources.hpp#L112](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/2ce7a6c6202518985ee50408fc5c586e01260ae2/src/Editor/Resources.hpp#L112): Unused private function: 'ResourceList::GetInstance' [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedPrivateFunction)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by NinjaDanz3r** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR][MINOR] AncientFungus:LGEPR: Cppcheck cannot find all the include files (use --check-config for details) [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AmissingInclude)
1. ![MINOR][MINOR] [Resources.hpp#L112](https://github.com/Chainsawkitten/LargeGameProjectEngine/blob/2a1ad74d46d81a04d077c4371f2da4c08c0da726/src/Editor/Resources.hpp#L112): Unused private function: 'ResourceList::GetInstance' [rule](http://localhost:9000/coding_rules#rule_key=cppcheck%3AunusedPrivateFunction)

[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'
